//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.21 at 12:58:37 PM CEST 
//


package molmed.xml.setup.legacy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sequenceingcenter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="platfrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uppmaxprojectid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uppmaxqos" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "sequenceingcenter",
    "platfrom",
    "uppmaxprojectid",
    "uppmaxqos"
})
@XmlRootElement(name = "metadata")
public class Metadata {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String sequenceingcenter;
    @XmlElement(required = true)
    protected String platfrom;
    @XmlElement(required = true)
    protected String uppmaxprojectid;
    @XmlElement(required = true)
    protected String uppmaxqos;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the sequenceingcenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceingcenter() {
        return sequenceingcenter;
    }

    /**
     * Sets the value of the sequenceingcenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceingcenter(String value) {
        this.sequenceingcenter = value;
    }

    /**
     * Gets the value of the platfrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatfrom() {
        return platfrom;
    }

    /**
     * Sets the value of the platfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatfrom(String value) {
        this.platfrom = value;
    }

    /**
     * Gets the value of the uppmaxprojectid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUppmaxprojectid() {
        return uppmaxprojectid;
    }

    /**
     * Sets the value of the uppmaxprojectid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUppmaxprojectid(String value) {
        this.uppmaxprojectid = value;
    }

    /**
     * Gets the value of the uppmaxqos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUppmaxqos() {
        return uppmaxqos;
    }

    /**
     * Sets the value of the uppmaxqos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUppmaxqos(String value) {
        this.uppmaxqos = value;
    }

}
