//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.19 at 11:26:29 AM CEST 
//


package molmed.xml.illuminareport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="AdapterPlot" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="AdapterPlotThumb" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="AvgQ" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BaseCompPlot" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BaseCompPlotThumb" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Cycles" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="DensityPF" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="DensityRaw" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="DupPlot" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DupPlotThumb" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ErrRate" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="ErrRateSD" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="GCPlot" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="GCPlotThumb" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LibraryName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PF" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="PctPF" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="PctQ30" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="Q30Fraction" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="Q30LengthMean" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="Q30LengthStdDev" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="Q30Plot" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Q30PlotThumb" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="QMean" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="QStdDev" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="QscorePlot" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="QscorePlotThumb" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="QscoreSum" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Raw" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Tag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="YieldPF" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="YieldQ30" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Read")
public class Read {

    @XmlAttribute(name = "AdapterPlot")
    protected String adapterPlot;
    @XmlAttribute(name = "AdapterPlotThumb")
    protected String adapterPlotThumb;
    @XmlAttribute(name = "AvgQ")
    protected String avgQ;
    @XmlAttribute(name = "BaseCompPlot")
    protected String baseCompPlot;
    @XmlAttribute(name = "BaseCompPlotThumb")
    protected String baseCompPlotThumb;
    @XmlAttribute(name = "Cycles")
    protected Integer cycles;
    @XmlAttribute(name = "DensityPF")
    protected Double densityPF;
    @XmlAttribute(name = "DensityRaw")
    protected Double densityRaw;
    @XmlAttribute(name = "DupPlot")
    protected String dupPlot;
    @XmlAttribute(name = "DupPlotThumb")
    protected String dupPlotThumb;
    @XmlAttribute(name = "ErrRate")
    protected Double errRate;
    @XmlAttribute(name = "ErrRateSD")
    protected Double errRateSD;
    @XmlAttribute(name = "GCPlot")
    protected String gcPlot;
    @XmlAttribute(name = "GCPlotThumb")
    protected String gcPlotThumb;
    @XmlAttribute(name = "Id")
    protected String id;
    @XmlAttribute(name = "LibraryName")
    protected String libraryName;
    @XmlAttribute(name = "PF")
    protected Integer pf;
    @XmlAttribute(name = "PctPF")
    protected Double pctPF;
    @XmlAttribute(name = "PctQ30")
    protected Double pctQ30;
    @XmlAttribute(name = "Q30Fraction")
    protected Double q30Fraction;
    @XmlAttribute(name = "Q30LengthMean")
    protected Double q30LengthMean;
    @XmlAttribute(name = "Q30LengthStdDev")
    protected Double q30LengthStdDev;
    @XmlAttribute(name = "Q30Plot")
    protected String q30Plot;
    @XmlAttribute(name = "Q30PlotThumb")
    protected String q30PlotThumb;
    @XmlAttribute(name = "QMean")
    protected Double qMean;
    @XmlAttribute(name = "QStdDev")
    protected Double qStdDev;
    @XmlAttribute(name = "QscorePlot")
    protected String qscorePlot;
    @XmlAttribute(name = "QscorePlotThumb")
    protected String qscorePlotThumb;
    @XmlAttribute(name = "QscoreSum")
    protected Integer qscoreSum;
    @XmlAttribute(name = "Raw")
    protected Integer raw;
    @XmlAttribute(name = "Tag")
    protected String tag;
    @XmlAttribute(name = "YieldPF")
    protected Integer yieldPF;
    @XmlAttribute(name = "YieldQ30")
    protected Integer yieldQ30;

    /**
     * Gets the value of the adapterPlot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdapterPlot() {
        return adapterPlot;
    }

    /**
     * Sets the value of the adapterPlot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdapterPlot(String value) {
        this.adapterPlot = value;
    }

    /**
     * Gets the value of the adapterPlotThumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdapterPlotThumb() {
        return adapterPlotThumb;
    }

    /**
     * Sets the value of the adapterPlotThumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdapterPlotThumb(String value) {
        this.adapterPlotThumb = value;
    }

    /**
     * Gets the value of the avgQ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvgQ() {
        return avgQ;
    }

    /**
     * Sets the value of the avgQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvgQ(String value) {
        this.avgQ = value;
    }

    /**
     * Gets the value of the baseCompPlot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseCompPlot() {
        return baseCompPlot;
    }

    /**
     * Sets the value of the baseCompPlot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseCompPlot(String value) {
        this.baseCompPlot = value;
    }

    /**
     * Gets the value of the baseCompPlotThumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseCompPlotThumb() {
        return baseCompPlotThumb;
    }

    /**
     * Sets the value of the baseCompPlotThumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseCompPlotThumb(String value) {
        this.baseCompPlotThumb = value;
    }

    /**
     * Gets the value of the cycles property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCycles() {
        return cycles;
    }

    /**
     * Sets the value of the cycles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCycles(Integer value) {
        this.cycles = value;
    }

    /**
     * Gets the value of the densityPF property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDensityPF() {
        return densityPF;
    }

    /**
     * Sets the value of the densityPF property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDensityPF(Double value) {
        this.densityPF = value;
    }

    /**
     * Gets the value of the densityRaw property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDensityRaw() {
        return densityRaw;
    }

    /**
     * Sets the value of the densityRaw property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDensityRaw(Double value) {
        this.densityRaw = value;
    }

    /**
     * Gets the value of the dupPlot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDupPlot() {
        return dupPlot;
    }

    /**
     * Sets the value of the dupPlot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDupPlot(String value) {
        this.dupPlot = value;
    }

    /**
     * Gets the value of the dupPlotThumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDupPlotThumb() {
        return dupPlotThumb;
    }

    /**
     * Sets the value of the dupPlotThumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDupPlotThumb(String value) {
        this.dupPlotThumb = value;
    }

    /**
     * Gets the value of the errRate property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getErrRate() {
        return errRate;
    }

    /**
     * Sets the value of the errRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setErrRate(Double value) {
        this.errRate = value;
    }

    /**
     * Gets the value of the errRateSD property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getErrRateSD() {
        return errRateSD;
    }

    /**
     * Sets the value of the errRateSD property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setErrRateSD(Double value) {
        this.errRateSD = value;
    }

    /**
     * Gets the value of the gcPlot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGCPlot() {
        return gcPlot;
    }

    /**
     * Sets the value of the gcPlot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGCPlot(String value) {
        this.gcPlot = value;
    }

    /**
     * Gets the value of the gcPlotThumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGCPlotThumb() {
        return gcPlotThumb;
    }

    /**
     * Sets the value of the gcPlotThumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGCPlotThumb(String value) {
        this.gcPlotThumb = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the libraryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibraryName() {
        return libraryName;
    }

    /**
     * Sets the value of the libraryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibraryName(String value) {
        this.libraryName = value;
    }

    /**
     * Gets the value of the pf property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPF() {
        return pf;
    }

    /**
     * Sets the value of the pf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPF(Integer value) {
        this.pf = value;
    }

    /**
     * Gets the value of the pctPF property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPctPF() {
        return pctPF;
    }

    /**
     * Sets the value of the pctPF property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPctPF(Double value) {
        this.pctPF = value;
    }

    /**
     * Gets the value of the pctQ30 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPctQ30() {
        return pctQ30;
    }

    /**
     * Sets the value of the pctQ30 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPctQ30(Double value) {
        this.pctQ30 = value;
    }

    /**
     * Gets the value of the q30Fraction property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getQ30Fraction() {
        return q30Fraction;
    }

    /**
     * Sets the value of the q30Fraction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQ30Fraction(Double value) {
        this.q30Fraction = value;
    }

    /**
     * Gets the value of the q30LengthMean property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getQ30LengthMean() {
        return q30LengthMean;
    }

    /**
     * Sets the value of the q30LengthMean property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQ30LengthMean(Double value) {
        this.q30LengthMean = value;
    }

    /**
     * Gets the value of the q30LengthStdDev property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getQ30LengthStdDev() {
        return q30LengthStdDev;
    }

    /**
     * Sets the value of the q30LengthStdDev property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQ30LengthStdDev(Double value) {
        this.q30LengthStdDev = value;
    }

    /**
     * Gets the value of the q30Plot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQ30Plot() {
        return q30Plot;
    }

    /**
     * Sets the value of the q30Plot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQ30Plot(String value) {
        this.q30Plot = value;
    }

    /**
     * Gets the value of the q30PlotThumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQ30PlotThumb() {
        return q30PlotThumb;
    }

    /**
     * Sets the value of the q30PlotThumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQ30PlotThumb(String value) {
        this.q30PlotThumb = value;
    }

    /**
     * Gets the value of the qMean property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getQMean() {
        return qMean;
    }

    /**
     * Sets the value of the qMean property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQMean(Double value) {
        this.qMean = value;
    }

    /**
     * Gets the value of the qStdDev property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getQStdDev() {
        return qStdDev;
    }

    /**
     * Sets the value of the qStdDev property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQStdDev(Double value) {
        this.qStdDev = value;
    }

    /**
     * Gets the value of the qscorePlot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQscorePlot() {
        return qscorePlot;
    }

    /**
     * Sets the value of the qscorePlot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQscorePlot(String value) {
        this.qscorePlot = value;
    }

    /**
     * Gets the value of the qscorePlotThumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQscorePlotThumb() {
        return qscorePlotThumb;
    }

    /**
     * Sets the value of the qscorePlotThumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQscorePlotThumb(String value) {
        this.qscorePlotThumb = value;
    }

    /**
     * Gets the value of the qscoreSum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getQscoreSum() {
        return qscoreSum;
    }

    /**
     * Sets the value of the qscoreSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQscoreSum(Integer value) {
        this.qscoreSum = value;
    }

    /**
     * Gets the value of the raw property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRaw() {
        return raw;
    }

    /**
     * Sets the value of the raw property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRaw(Integer value) {
        this.raw = value;
    }

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTag(String value) {
        this.tag = value;
    }

    /**
     * Gets the value of the yieldPF property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getYieldPF() {
        return yieldPF;
    }

    /**
     * Sets the value of the yieldPF property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setYieldPF(Integer value) {
        this.yieldPF = value;
    }

    /**
     * Gets the value of the yieldQ30 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getYieldQ30() {
        return yieldQ30;
    }

    /**
     * Sets the value of the yieldQ30 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setYieldQ30(Integer value) {
        this.yieldQ30 = value;
    }

}
