//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.19 at 11:26:29 AM CEST 
//


package molmed.xml.illuminareport;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{illuminareport.xml.molmed}Read" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CasavaVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ClusterKitVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CsVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FlowCellId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FlowCellVer" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="InstrumentModel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Project" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Qoffset" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="RtaVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RunFolder" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SBSversion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SisyphusVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "read"
})
@XmlRootElement(name = "MetaData")
public class MetaData {

    @XmlElement(name = "Read", required = true)
    protected List<Read> read;
    @XmlAttribute(name = "CasavaVersion")
    protected String casavaVersion;
    @XmlAttribute(name = "ClusterKitVersion")
    protected String clusterKitVersion;
    @XmlAttribute(name = "CsVersion")
    protected String csVersion;
    @XmlAttribute(name = "FlowCellId")
    protected String flowCellId;
    @XmlAttribute(name = "FlowCellVer")
    protected String flowCellVer;
    @XmlAttribute(name = "InstrumentModel")
    protected String instrumentModel;
    @XmlAttribute(name = "Project")
    protected String project;
    @XmlAttribute(name = "Qoffset")
    protected Integer qoffset;
    @XmlAttribute(name = "RtaVersion")
    protected String rtaVersion;
    @XmlAttribute(name = "RunFolder")
    protected String runFolder;
    @XmlAttribute(name = "SBSversion")
    protected String sbSversion;
    @XmlAttribute(name = "SisyphusVersion")
    protected String sisyphusVersion;

    /**
     * Gets the value of the read property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the read property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRead().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Read }
     * 
     * 
     */
    public List<Read> getRead() {
        if (read == null) {
            read = new ArrayList<Read>();
        }
        return this.read;
    }

    /**
     * Gets the value of the casavaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCasavaVersion() {
        return casavaVersion;
    }

    /**
     * Sets the value of the casavaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCasavaVersion(String value) {
        this.casavaVersion = value;
    }

    /**
     * Gets the value of the clusterKitVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClusterKitVersion() {
        return clusterKitVersion;
    }

    /**
     * Sets the value of the clusterKitVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClusterKitVersion(String value) {
        this.clusterKitVersion = value;
    }

    /**
     * Gets the value of the csVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsVersion() {
        return csVersion;
    }

    /**
     * Sets the value of the csVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsVersion(String value) {
        this.csVersion = value;
    }

    /**
     * Gets the value of the flowCellId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlowCellId() {
        return flowCellId;
    }

    /**
     * Sets the value of the flowCellId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlowCellId(String value) {
        this.flowCellId = value;
    }

    /**
     * Gets the value of the flowCellVer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlowCellVer() {
        return flowCellVer;
    }

    /**
     * Sets the value of the flowCellVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlowCellVer(String value) {
        this.flowCellVer = value;
    }

    /**
     * Gets the value of the instrumentModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentModel() {
        return instrumentModel;
    }

    /**
     * Sets the value of the instrumentModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentModel(String value) {
        this.instrumentModel = value;
    }

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProject() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProject(String value) {
        this.project = value;
    }

    /**
     * Gets the value of the qoffset property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getQoffset() {
        return qoffset;
    }

    /**
     * Sets the value of the qoffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQoffset(Integer value) {
        this.qoffset = value;
    }

    /**
     * Gets the value of the rtaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtaVersion() {
        return rtaVersion;
    }

    /**
     * Sets the value of the rtaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtaVersion(String value) {
        this.rtaVersion = value;
    }

    /**
     * Gets the value of the runFolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunFolder() {
        return runFolder;
    }

    /**
     * Sets the value of the runFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunFolder(String value) {
        this.runFolder = value;
    }

    /**
     * Gets the value of the sbSversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSBSversion() {
        return sbSversion;
    }

    /**
     * Sets the value of the sbSversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSBSversion(String value) {
        this.sbSversion = value;
    }

    /**
     * Gets the value of the sisyphusVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSisyphusVersion() {
        return sisyphusVersion;
    }

    /**
     * Sets the value of the sisyphusVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSisyphusVersion(String value) {
        this.sisyphusVersion = value;
    }

}
