//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.21 at 01:29:40 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "setup.xml.molmed", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package molmed.xml.setup;
