//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.15 at 04:12:51 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "setup.xml.molmed", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package molmed.xml.setup;
